# Google Cloud Build configuration
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/reviewscope-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/reviewscope-backend:latest'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/reviewscope-backend:$COMMIT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'reviewscope-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/reviewscope-backend:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300s'
      - '--max-instances'
      - '3'
      - '--min-instances'
      - '0'

images:
  - 'gcr.io/$PROJECT_ID/reviewscope-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/reviewscope-backend:latest'
